name: Quick commerse

on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd client && npm install
          cd ../server && npm install

      - name: Run Tests
        run: |
          cd client && npm test
          cd ../server && npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend (Vercel)
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Backend (Render)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
